In [1]:
import pandas as pd

**Получаем данные по одной категории и сохраняем их**

In [2]:
doc_name = ['brands', 'categories', 'items', 'reviews', 'students', 'tasks']
category_id = 21

In [69]:
df_cat = pd.read_csv('yamarket/categories.csv')
print(df_cat[df_cat['id'] == category_id])
len(df_cat)

    id                name
20  21  Мобильные телефоны

3006

In [71]:
brands = pd.read_csv('yamarket/brands.csv')
brands.head()

   id     name  category
0   1      IGC         1
1   2  Philips         2
2   3  Xinbida         3
3   4  INCOTEX         4
4   5    Hurom         5

In [3]:
df_items = pd.read_csv('yamarket/items.csv')
df_items.head()

,id,prod_id,name,description,imgs,url,price,specifications,params,reviews,keywords,brand,category
0,1,1721634222,Настенная сплит-система IGC RAS-09NHM / RAC-09NHM,Настенная сплит-система IGC RAS-09NHM / RAC-09...,NaN,https://market.yandex.ru/product--nastennaia-s...,23700,обогрев и охлаждение помещений до 26м²;режим в...,"[{""\u041e\u0441\u043d\u043e\u0432\u043d\u044b\...",1;2;3;4;5;6;7;8;9;10;11;12;13;14;15;16;17;18;1...,NaN,1,1
1,2,1806586027,Робот-пылесос Philips FC8822 SmartPro Active,Робот-пылесос Philips FC8822 SmartPro Active —...,https://avatars.mds.yandex.net/get-mpic/466729...,https://market.yandex.ru/product--robot-pyleso...,25990,сухая уборка;контейнер для пыли 0.40 л;время р...,"[{""\u041f\u043e\u0434\u0440\u043e\u0431\u043d\...",38;39;40;41;42;43;44;45;46;47;48;49;50;51;52;5...,NaN,2,2
2,3,654846023,Магнитный конструктор Xinbida Magical Magnet 7...,Магнитный конструктор Xinbida Magical Magnet 7...,https://avatars.mds.yandex.net/get-mpic/167380...,https://market.yandex.ru/product--magnitnyi-ko...,0,"от 3 лет;навыки: логика и мышление, интерес к ...","[{""\u041e\u0431\u0449\u0438\u0435 \u0445\u0430...",75;76;,NaN,3,3
3,4,189295201,Счетчик электроэнергии однофазный однотарифный...,Счетчик электроэнергии однофазный однотарифный...,https://avatars.mds.yandex.net/get-mpic/154540...,https://market.yandex.ru/product--schetchik-el...,625,принцип работы: электромеханический;класс точн...,"[{""\u041e\u0431\u0449\u0438\u0435 \u0445\u0430...",77;78;79;80;81;82;83;84;85;86;87;88;89;90;91;92;,NaN,4,4
4,5,13204608,Соковыжималка Hurom HV 2G SBE-14/LBE-14/EBE-14,Соковыжималка Hurom HV 2G SBE-14/LBE-14/EBE-14...,https://avatars.mds.yandex.net/get-mpic/364668...,https://market.yandex.ru/product--sokovyzhimal...,0,комбинированная соковыжималка;мощность 150 Вт;...,"[{""\u0422\u0435\u0445\u043d\u0438\u0447\u0435\...",93;94;95;96;97;,NaN,5,5

In [16]:
df_items.groupby('category')['id'].count()

category
1       3620
2        524
3       2197
4         32
5        295
6       6112
7         40
8         12
9        862
10      1210
11       187
12       216
13       792
14      4164
15      3772
16       218
17      2604
18      1629
19        87
20       616
21      8651
22        68
23      2676
24      3846
25      1235
26      8175
27       565
28       147
29      2431
30       737
        ...
2977       1
2978       1
2979       1
2980       1
2981       2
2982       2
2983       1
2984       1
2985       1
2986       2
2987       1
2988       1
2989       1
2990       1
2991       1
2992       1
2993       1
2994       2
2995       1
2996       1
2997       1
2998       2
2999       1
3000       1
3001       1
3002       1
3003       1
3004       1
3005       1
3006       2
Name: id, Length: 3006, dtype: int64

In [12]:
data = df_items[df_items['category'] == category_id].drop(['id', 'name', 'description',
                                                           'imgs', 'url', 'specifications',
                                                           'params', 'keywords', 'category'], 1)
data.head()

,prod_id,price,reviews,brand
22,10692976,0,280;281;282;283;284;285;286;287;288;289;290;29...,23
60,500943043,0,539;540;541;,74
220,11169281,0,1413;1414;,209
310,1037289,0,2081;2083;2085;2087;2090;2092;2094;,296
361,997628,0,2316;2317;2318;2319;2320;2321;2322;2323;2324;,340

In [21]:
data[data['price'] != 0].head()

,prod_id,price,reviews,brand
745,1721074988,21290,4734;4735;4736;4737;4738;4739;4740;4741;4742;4...,681
1130,165765775,1199,7170;,1033
1405,657015038,1335,8808;,711
1699,484948063,6300,10342;10343;10344;10345;10346;10347;10348;1034...,74
2134,235550027,735,12640;12641;12642;12643;12644;12645;12646;1264...,1834

In [23]:
data.to_csv('yamarket/small_items_{}.csv'.format(category_id))

**Загрузим предыдущую категорию и сопоставим df_items & df_review**

In [12]:
df_items = pd.read_csv('yamarket/small_items_21.csv')
del df_items['Unnamed: 0']
df_items.head()

     prod_id  price                                            reviews  brand
0   10692976      0  280;281;282;283;284;285;286;287;288;289;290;29...     23
1  500943043      0                                       539;540;541;     74
2   11169281      0                                         1413;1414;    209
3    1037289      0                2081;2083;2085;2087;2090;2092;2094;    296
4     997628      0      2316;2317;2318;2319;2320;2321;2322;2323;2324;    340

In [58]:
new_df_items = pd.DataFrame()
for_concat = []
for i in range(len(df_items)) :
    if (i % 200 == 0) :
        print(i)
    y = df_items.loc[i]
    if ';' in str(y['reviews']) :
        for j in y['reviews'].split(';') :
            x = df_items[df_items['prod_id'] == y['prod_id']].drop('reviews', 1)
            if (j == '') :
                continue
            x['reviews_id'] = int(j)
            #print(x.head())
            for_concat.append(x)

0
200
400
600
800
1000
1200
1400
1600
1800
2000
2200
2400
2600
2800
3000
3200
3400
3600
3800
4000
4200
4400
4600
4800
5000
5200
5400
5600
5800
6000
6200
6400
6600
6800
7000
7200
7400
7600
7800
8000
8200
8400
8600

In [59]:
new_df_items = pd.concat(for_concat, 0)
new_df_items.head(10)

    prod_id  price  brand  reviews_id
0  10692976      0     23         280
0  10692976      0     23         281
0  10692976      0     23         282
0  10692976      0     23         283
0  10692976      0     23         284
0  10692976      0     23         285
0  10692976      0     23         286
0  10692976      0     23         287
0  10692976      0     23         288
0  10692976      0     23         289

In [38]:
df_reviews = pd.read_csv('yamarket/reviews.csv')
df_reviews.head()

,id,author,description,imgs,rate,date
0,1,даниил л.,Достоинства: Тихий внутренний блок (если включ...,NaN,1,2020-07-06
1,2,Рамиль Г.,"Достоинства: Тихий, даже на максимальной мощно...",NaN,5,2018-08-22
2,3,Юрий К.,"Достоинства: качество, цена, уровень шума, удо...",NaN,5,2017-07-29
3,4,Алина К.,Достоинства: Низкая цена \n\nНедостатки: Нет \...,NaN,5,2017-07-22
4,5,Ульна О.,"Достоинства: цена, мощность, компактность, диз...",NaN,5,2017-06-26

In [60]:
new_df_items.head()

    prod_id  price  brand  reviews_id
0  10692976      0     23         280
0  10692976      0     23         281
0  10692976      0     23         282
0  10692976      0     23         283
0  10692976      0     23         284

In [61]:
data = pd.merge(new_df_items, df_reviews, left_on = 'reviews_id', right_on = 'id', how = 'outer')

In [62]:
del data['reviews_id']
del data['imgs']
data.head()

,prod_id,price,brand,id,author,description,rate,date
0,10692976.0,0.0,23.0,280,Konstantin Zeleznov,"Достоинства: Большой экран, 2-сим карты mini, ...",4,2014-03-04
1,10692976.0,0.0,23.0,281,Юлия Л.,Достоинства: Очень много. Плохие углы обзора з...,5,2014-03-22
2,10692976.0,0.0,23.0,282,Имя скрыто,"Достоинства: 5 дюймовый экран, Android 4.2, вх...",5,2014-05-18
3,10692976.0,0.0,23.0,283,роман п.,"Достоинства: Давольно неприхотливая модель, уд...",5,2014-03-28
4,10692976.0,0.0,23.0,284,Александр Н.,"Достоинства: Экран 5"", процессор справляется н...",4,2014-02-24

In [65]:
data_without_nan = data[data['prod_id'] == data['prod_id']]

In [66]:
data_without_nan.to_csv('data_{}.csv'.format(category_id))

In [67]:
data_without_nan

,prod_id,price,brand,id,author,description,rate,date
0,10692976.0,0.0,23.0,280,Konstantin Zeleznov,"Достоинства: Большой экран, 2-сим карты mini, ...",4,2014-03-04
1,10692976.0,0.0,23.0,281,Юлия Л.,Достоинства: Очень много. Плохие углы обзора з...,5,2014-03-22
2,10692976.0,0.0,23.0,282,Имя скрыто,"Достоинства: 5 дюймовый экран, Android 4.2, вх...",5,2014-05-18
3,10692976.0,0.0,23.0,283,роман п.,"Достоинства: Давольно неприхотливая модель, уд...",5,2014-03-28
4,10692976.0,0.0,23.0,284,Александр Н.,"Достоинства: Экран 5"", процессор справляется н...",4,2014-02-24
5,10692976.0,0.0,23.0,285,Иван У.,"Достоинства: Прилично выглядит, приличное изоб...",4,2014-06-19
6,10692976.0,0.0,23.0,286,Любовь К.,Достоинства: Отличный телефон. Пользуюсь полго...,5,2015-06-09
7,10692976.0,0.0,23.0,287,Юрий Сергеев,"Достоинства: 2 слота sim, экран 5 дюймов, диза...",4,2014-04-10
8,10692976.0,0.0,23.0,288,Имя скрыто,"Достоинства: 2 сим-карты, экран 5 дюймов \n\nН...",4,2014-02-23
9,10692976.0,0.0,23.0,289,David Razmadze,"Достоинства: Цена, возможность ставить игры на...",3,2014-02-18
10,10692976.0,0.0,23.0,290,Николай С.,"Достоинства: Хорошо держит батарею,яркий экран...",3,2015-01-02
11,10692976.0,0.0,23.0,291,Имя скрыто,Достоинства: 5 дюймов экран \n\nНедостатки: ди...,3,2015-07-17
12,10692976.0,0.0,23.0,292,Вадим Думенов,"Достоинства: 1) Не знаю кто там говорит, что к...",4,2015-04-15
13,10692976.0,0.0,23.0,293,Юлия Ф.,Достоинства: Экран \n\nНедостатки: Плохое каче...,1,2015-03-20
14,10692976.0,0.0,23.0,294,Александр С.,Достоинства: большой дисплей \n\nНедостатки: б...,5,2014-05-09
15,10692976.0,0.0,23.0,295,Сергей Валуев,"Достоинства: экран и размер, работа GPS на отл...",5,2014-12-30
16,10692976.0,0.0,23.0,296,Александр К.,Достоинства: мощный телефон по антуту мощнее а...,3,2014-10-21
17,10692976.0,0.0,23.0,297,Родион К.,"Достоинства: Надежность, ударопрочность, батар...",4,2018-07-06
18,10692976.0,0.0,23.0,298,Вадим Думенов,"Достоинства: Уже писал здесь отзыва, ещё раз п...",3,2016-05-19
19,500943043.0,0.0,74.0,539,Константин Иванов,Достоинства: - Качественный AMOLED дисплей.\n-...,5,2019-10-22
20,500943043.0,0.0,74.0,540,Hakuna Matata,"Достоинства: Быстро заряжается, заряда хватает...",5,2019-10-05
21,500943043.0,0.0,74.0,541,Ксения С.,\n\nКомментарий: Телефон просто бомба такой бе...,5,2020-01-08
22,11169281.0,0.0,209.0,1413,Имя скрыто,"Достоинства: Яркий большой экран, удобно лежит...",2,2014-12-13
23,11169281.0,0.0,209.0,1414,Василий Т.,Достоинства: - яркий экран (читабельно даже на...,2,2015-08-31
24,1037289.0,0.0,296.0,2081,Елена,"Достоинства: хороший простой телефон, звук нор...",4,2009-02-18
25,1037289.0,0.0,296.0,2083,слава ч.,Достоинства: 1)громкая музыка 2)скачивоется мн...,4,2009-10-04
26,1037289.0,0.0,296.0,2085,Имя скрыто,Достоинства: Аккумулятор и быстродействие.. не...,4,2012-02-28
27,1037289.0,0.0,296.0,2087,Александр Малышев,Достоинства: неубиваем \n\nНедостатки: плохой ...,4,2011-01-14
28,1037289.0,0.0,296.0,2090,"Ножи.Производство,продажа,сервис,заказ.",Достоинства: подойдёт для подростка.маленький....,4,2008-08-18
29,1037289.0,0.0,296.0,2092,Татьяна В.,Достоинства: компактный \n\nНедостатки: 1)поме...,2,2009-01-14
...,...,...,...,...,...,...,...,...
314163,175944418.0,47250.0,2474.0,2916284,Имя скрыто,"Достоинства: Экран, быстрая работа, жестовое у...",5,2019-01-14
314164,175944418.0,47250.0,2474.0,2916285,Игорь Л.,Достоинства: Качество картинки на достойном ур...,5,2020-04-09
314165,175944418.0,47250.0,2474.0,2916286,Александр Карпенко,Достоинства: 1. Приятные тактильные ощущения\n...,5,2020-06-07
314166,175944418.0,47250.0,2474.0,2916287,Имя скрыто,"Достоинства: Плавная работа, хорошая производи...",2,2020-06-05
314167,175944418.0,47250.0,2474.0,2916288,Schweppes,Достоинства: Камера\nДисплей\nРазмер и вес тел...,5,2019-03-07
314168,175944418.0,47250.0,2474.0,2916289,Альфонсо И.,Достоинства: Дизайн+ тактильные ощущения от ус...,5,2019-03-04
314169,175944418.0,47250.0,2474.0,2916290,Артем С.,Достоинства: 1. Производительность. Как ни кру...,3,2020-02-16
314170,175944418.0,47250.0,2474.0,2916291,Виктория Я.,"Достоинства: скорость процессора, время работы...",5,2020-07-25
314171,175944418.0,47250.0,2474.0,2916292,Ranis Yarullin,Достоинства: Достойный аппарат \n\nНедостатки:...,5,2020-07-10
314172,175944418.0,47250.0,2474.0,2916293,Pavel,"Достоинства: - аккумулятор, вывозит при обычно...",5,2020-06-02
314173,175944418.0,47250.0,2474.0,2916294,Руслан Нугуманов,"Достоинства: -IPS экран. Да, у него довольно т...",5,2020-04-28
314174,175944418.0,47250.0,2474.0,2916295,Имя скрыто,"Достоинства: достоинства, ну наверно экран с к...",2,2020-04-15
314175,175944418.0,47250.0,2474.0,2916296,Борис Аркадьевич Ш.,Достоинства: Подарили дочери на юбилей. Счасть...,5,2019-11-18
314176,175944418.0,47250.0,2474.0,2916297,Alesana,Достоинства: На данный момент самый лучший по ...,5,2019-10-31
314177,175944418.0,47250.0,2474.0,2916298,Максим Оганов,\n\nКомментарий: Бюджетник оказался совсем не ...,5,2019-09-21
314178,175944418.0,47250.0,2474.0,2916299,Dude D.,Достоинства: -автономность\n-размер аппарата\n...,3,2019-06-17
314179,175944418.0,47250.0,2474.0,2916300,Татьяна М.,"Достоинства: Большой хороший экран, батарея де...",5,2019-06-10
314180,175944418.0,47250.0,2474.0,2916301,Юрий Троль,"Достоинства: Айфон лучший,мощный,отличная каме...",5,2019-02-27
314181,175944418.0,47250.0,2474.0,2916302,Тимур,Достоинства: 1) производительность лучше чем x...,5,2019-01-18
314182,175944418.0,47250.0,2474.0,2916303,БОРИС,Достоинства: Узнаваемый дизайн\nХватает заряда...,5,2019-01-09
314183,175944418.0,47250.0,2474.0,2916304,Мария К.,"Достоинства: Дизайн, пожалуй, лучший из всех а...",5,2018-11-08
314184,175944418.0,47250.0,2474.0,2916305,Дмитрий В.,Достоинства: Одни плюсы честного говоря. Соотн...,5,2018-10-28
314185,175944418.0,47250.0,2474.0,2916306,Олег Б.,"Достоинства: Хорошая камера, громкий звук, бат...",3,2020-02-03
314186,175944418.0,47250.0,2474.0,2916307,Таня П.,Достоинства: Супер новинка от айфон! В этом те...,5,2018-11-10
314187,175944418.0,47250.0,2474.0,2916308,lera haski,"Достоинства: Приятный дизайн, широкий функцион...",5,2020-04-07
314188,175944418.0,47250.0,2474.0,2916309,Имя скрыто,Достоинства: Сравнивать буду с китайскими флаг...,3,2019-08-29
314189,175944418.0,47250.0,2474.0,2916310,Кирилл Х.,Достоинства: Камера\nЭкран\nFace ID\nДа мать е...,5,2019-01-28
314190,175944418.0,47250.0,2474.0,2916311,Иван Бирюков,"Достоинства: Приятный на ощупь, хороший звук, ...",5,2020-07-24
314191,175944418.0,47250.0,2474.0,2916312,Имя скрыто,"Достоинства: Мощный, быстрый, долго держит зар...",3,2019-11-04
314192,175944418.0,47250.0,2474.0,2916313,Дмитрий Белешев,Достоинства: 1. Большой и качественный дисплей...,5,2019-08-24